# Generated by Django 3.0.8 on 2020-08-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200803_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='has_sizes',
        ),
        migrations.RemoveField(
            model_name='event',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sku',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
